# NumPy 정리

---

## 1. NumPy란 무엇인가
NumPy는 Python에서 대규모 수치 계산을 빠르게 처리하기 위한 라이브러리이다.
Python의 기본 리스트보다 훨씬 빠른 연산이 가느하다.

핵심 특징은 다음과 같다 :
- 다차원 배열 지원
- 빠른 벡터 연산
- 선형대수 연산 지원
- 과학 계산 라이브러리의 기반
특히 머신러닝과 데이터 분석에서는 대부분 **NumPy 기반으로 계산이 이루어진다.**

---



In [1]:
# NumPy import
import numpy as np

## 2. ndarray (NumPy의 핵심 자료구조)
NumPy의 기본 데이터 구조는 **ndarray (N-dimensional array)** 이다.

Python 리스트와는 다음과 같은 차이가 존재한다 :
| 구분     | Python List | NumPy Array |
| ------ | ----------- | ----------- |
| 속도     | 느림          | 빠름          |
| 연산     | 반복문 필요      | 벡터 연산 가능    |
| 데이터 타입 | 혼합 가능       | 일반적으로 동일 타입 |

---

##### 배열 생성은 다음과 같이 한다.

In [6]:
arr = np.array([1, 2, 3, 4])

print(arr)

[1 2 3 4]


출력

```python
array([1, 2, 3, 4])
````

---

## 3. 배열의 차원

NumPy 배열은 **여러 차원(Dimension)** 을 가질 수 있다.\
차원은 데이터를 구성하는 **축(axis)의 개수**라고 생각하면 된다.

In [ ]:
# 1차원 배열
arr_1 = np.array([1, 2, 3])

# 2차원 배열
arr_2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 3차원 배열
arr_3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

---

## 4. ndarray의 주요 속성

NumPy의 핵심 자료구조인 `ndarray` 는 배열의 구조와 특징을 확인할 수 있는 여러 속성을 제공한다.\
배열을 다룰 때는 단순히 값만 보는 것이 아니라, **배열의 모양, 차원, 크기, 자료형**을 함께 이해하는 것이 중요하다.\
\
이번에는 다음 4가지 주요 속성을 정리한다.

- `shape` : 배열의 구조
- `ndim` : 배열의 차원 수
- `size` : 전체 원소 개수
- `dtype` : 배열 원소의 자료형


In [14]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


# -------------------------------------------------
# shape = 배열의 구조 (각 차원별 데이터 개수)
# shape는 튜플(tuple) 형태로 반환된다.
# (행 개수, 열 개수) 형태로 나타난다.
# 즉 현재 배열은 2행 3열 구조이다.
print(arr.shape) # (2, 3) = 2행 3열

# 의미
# 2 -> 행(row)의 개수
# 3 -> 열(column)의 개수

# shape는 다음과 같은 상황에서 중요하다.
# 1) 배열 구조 확인
# 2) reshape 사용 전 구조 파악
# 3) 행렬 연산 가능 여부 확인
# 4) 머신러닝 데이터 형태 확인

# -------------------------------------------------
# ndim = 배열의 차원
print(arr.ndim) # 2 = 2차원

# 의미
# 이 배열은 2차원 배열이다.

# 차원 예시
# 1차원 → 벡터 형태
# [1, 2, 3]

# 2차원 → 행렬 형태
# [[1,2,3],
#  [4,5,6]]

# 3차원 → 2차원 배열이 여러 개 쌓인 구조
# [[[1,2],[3,4]],
#  [[5,6],[7,8]]]

# -------------------------------------------------
# size = 전체 원소 개수
print(arr.size) # 6

# 현재 배열 구조는 (2,3)
# 따라서 원소 개수는
# 2 * 3 = 6

# size는 다음 상황에서 유용하다.
# 1) 전체 데이터 개수 확인
# 2) reshape 가능 여부 판단
# 3) 데이터 규모 확인

# -------------------------------------------------
# dtype = 데이터 타입
print(arr.dtype) # int64

# 의미
# 배열의 모든 값이 64비트 정수형(int64)으로 저장된다.

# dtype 예시
# int32   → 32비트 정수
# int64   → 64비트 정수
# float32 → 32비트 실수
# float64 → 64비트 실수

# dtype은 다음에 영향을 준다.
# 1) 메모리 사용량
# 2) 연산 속도
# 3) 계산 결과 정확도

# -------------------------------------------------
# dtype 자동 변환 예시
# NumPy는 배열을 만들 때 데이터 타입을 자동으로 결정한다.
a = np.array([1, 2, 3])
print(a.dtype)  # 정수형

b = np.array([1.0, 2.0, 3.0])
print(b.dtype)  # 실수형

c = np.array([1, 2, 3.5])
print(c.dtype)  # 정수 + 실수 → 실수형으로 자동 변환

(2, 3)
2
6
int64
int64
float64
float64


---

## 5. NumPy 배열 생성 방법


In [ ]:
# -------------------------------------------------
# np.zeros() = 0으로 채운 배열 생성
# shape를 인자로 받아 해당 구조에 맞는 배열을 만든다.
# 초기값이 전부 0이기 때문에
# 빈 배열처럼 시작하고 싶을 때 자주 사용한다.
zero_arr = np.zeros((2, 3))
print(zero_arr)
# [[0. 0. 0.]
#  [0. 0. 0.]]

# 의미
# (2, 3) → 2행 3열 배열 생성
# 모든 값이 0으로 채워진다.

# 주의
# 기본 dtype은 float이다.
print(zero_arr.dtype)   # float64

# 정수형으로 만들고 싶으면 dtype을 직접 지정할 수 있다.
zero_int_arr = np.zeros((2, 3), dtype=int)
print(zero_int_arr)
# [[0 0 0]
#  [0 0 0]]

# np.zeros()가 유용한 상황
# 1) 특정 크기의 배열을 미리 만들고 싶을 때
# 2) 계산 결과를 저장할 빈 배열이 필요할 때
# 3) 동적 계획법, 이미지 처리, 행렬 계산 등에서 초기값 설정이 필요할 때



# -------------------------------------------------
# np.ones() = 1로 채운 배열 생성
# shape를 인자로 받아 해당 구조에 맞는 배열을 만들고
# 모든 값을 1로 채운다.
one_arr = np.ones((3, 3))
print(one_arr)
# [[1. 1. 1.]
#  [1. 1. 1.]
#  [1. 1. 1.]]

# 의미
# (3, 3) → 3행 3열 배열 생성
# 모든 값이 1로 채워진다.

# 역시 기본 dtype은 float이다.
print(one_arr.dtype)    # float64

# dtype 지정 가능
one_int_arr = np.ones((3, 3), dtype=int)
print(one_int_arr)
# [[1 1 1]
#  [1 1 1]
#  [1 1 1]]

# np.ones()가 유용한 상황
# 1) 가중치 초기값 설정
# 2) 마스크 배열 생성
# 3) 일정한 기본값으로 시작하는 계산


# 네 코드에서 변수명이 identity_arr 였는데
# 사실 np.ones((3, 3))는 단위행렬(identity matrix)이 아니다.
# 그냥 모든 값이 1인 행렬이다.
#
# 단위행렬은 대각선만 1이고 나머지는 0인 행렬이다.
# 그건 np.eye()로 만든다.
identity_matrix = np.eye(3)
print(identity_matrix)
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]



# -------------------------------------------------
# np.arange() = 일정한 간격의 값으로 배열 생성
# Python의 range()와 비슷하지만 결과가 NumPy 배열로 나온다.
arange_arr = np.arange(0, 10)
print(arange_arr)   # [0 1 2 3 4 5 6 7 8 9]

# 의미
# 시작값: 0
# 끝값: 10 (포함하지 않음)
# 간격(step): 기본값 1

# step을 직접 지정할 수도 있다.
arange_step_arr = np.arange(0, 10, 2)
print(arange_step_arr)  # [0 2 4 6 8]

# 음수 step도 가능하다.
arange_reverse_arr = np.arange(10, 0, -2)
print(arange_reverse_arr)   # [10  8  6  4  2]

# np.arange()가 유용한 상황
# 1) 연속된 정수 배열 생성
# 2) 인덱스 배열 생성
# 3) 규칙적인 수열 데이터 생성

# 주의
# arange는 끝값을 포함하지 않는다.
# np.arange(0, 5) → [0 1 2 3 4]



# -------------------------------------------------
# np.linspace() = 구간을 균등하게 나누어 배열 생성
# 시작값과 끝값 "사이"를 num개로 균등 분할한다.
linspace_arr = np.linspace(0, 1, 5)
print(linspace_arr)   # [0.   0.25 0.5  0.75 1.  ]

# 의미
# 시작값: 0
# 끝값: 1
# 총 5개의 값을 균등한 간격으로 생성

# np.linspace()는 끝값을 포함하는 것이 기본이다.
# 즉, 0과 1 사이를 5등분한 값이 아니라
# 0부터 1까지 포함해서 총 5개의 점을 만든다.

# 각 값 사이의 간격
# 0.25, 0.25, 0.25, 0.25

# 예시 2
linspace_arr2 = np.linspace(1, 10, 4)
print(linspace_arr2)
# [ 1.  4.  7. 10.]

# endpoint=False를 주면 끝값을 포함하지 않을 수도 있다.
linspace_no_end = np.linspace(0, 1, 5, endpoint=False)
print(linspace_no_end)
# [0.  0.2 0.4 0.6 0.8]

# np.linspace()가 유용한 상황
# 1) 그래프 그릴 x축 값 생성
# 2) 실수 구간을 일정하게 나눌 때
# 3) 수학 함수 실험, 시뮬레이션, 공학 계산



# -------------------------------------------------
# np.arange() 와 np.linspace() 차이
#
# np.arange()
# - 간격(step)을 기준으로 배열 생성
# - 끝값은 포함하지 않음
#
# np.linspace()
# - 개수(num)를 기준으로 배열 생성
# - 기본적으로 끝값을 포함함
#
# 예시 비교
print(np.arange(0, 1, 0.2))      # [0.  0.2 0.4 0.6 0.8]
print(np.linspace(0, 1, 6))      # [0.  0.2 0.4 0.6 0.8 1. ]



# -------------------------------------------------
# 추가로 같이 알아두면 좋은 배열 생성 함수
# np.full() = 특정 값으로 채운 배열 생성
full_arr = np.full((2, 3), 7)
print(full_arr)
# [[7 7 7]
#  [7 7 7]]

# np.empty() = 초기화되지 않은 배열 생성
# 값이 쓰레기값처럼 보일 수 있다.
# 빠르지만 초보 단계에서는 조심해서 써야 한다.
empty_arr = np.empty((2, 3))
print(empty_arr)

# np.eye() = 단위행렬 생성
eye_arr = np.eye(4)
print(eye_arr)

---

## 6. 배열 인덱싱과 슬라이싱


In [12]:

# -------------------------------------------------
# 1차원 배열 인덱싱
arr = np.array([10, 20, 30, 40, 50])

# 배열 구조
# [10, 20, 30, 40, 50]

# 인덱스 번호
#  0   1   2   3   4

# 특정 위치의 값 선택
print(arr[1])   # 20

# 의미
# arr[1] → 인덱스 1에 있는 값


# -------------------------------------------------
# 음수 인덱싱
# NumPy는 뒤에서부터 접근하는 것도 가능하다.

print(arr[-1])  # 50
print(arr[-2])  # 40

# 의미
# -1 → 마지막 원소
# -2 → 뒤에서 두 번째 원소


# -------------------------------------------------
# 슬라이싱
# 형식
# 배열[start : end]

print(arr[1:4])  # [20 30 40]

# 의미
# 시작 인덱스 → 포함
# 끝 인덱스 → 포함하지 않음

# 즉
# arr[1:4] → 1,2,3 인덱스 선택


# -------------------------------------------------
# 슬라이싱 다양한 예시

print(arr[:3])   # [10 20 30]
# 처음부터 3번 전까지

print(arr[2:])   # [30 40 50]
# 2번부터 끝까지

print(arr[:])    # 전체 배열


# -------------------------------------------------
# 슬라이싱 간격(step) 지정
# 형식
# 배열[start : end : step]

print(arr[0:5:2])  # [10 30 50]

# 의미
# 0부터 5 전까지
# 2칸씩 이동하면서 선택


# -------------------------------------------------
# 2차원 배열 인덱싱
arr_2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 배열 구조
# [
#  [1, 2, 3],
#  [4, 5, 6]
# ]

# 인덱스 구조
# 행(row), 열(column)


# -------------------------------------------------
# 행 선택

print(arr_2[0])   # [1 2 3]

# 의미
# 0번째 행 선택

print(arr_2[1])   # [4 5 6]

# 1번째 행 선택


# -------------------------------------------------
# 특정 위치 값 선택

print(arr_2[1,2])  # 6

# 의미
# 1번째 행
# 2번째 열


# -------------------------------------------------
# 열 선택

print(arr_2[:,1])  # [2 5]

# 의미
# : → 모든 행 선택
# 1 → 두 번째 열 선택


# -------------------------------------------------
# 특정 행의 일부 선택

print(arr_2[0, 1:3])  # [2 3]

# 의미
# 0번째 행에서
# 1~2 인덱스 열 선택


# -------------------------------------------------
# 부분 행렬 선택

print(arr_2[:, 1:3])

# 결과
# [[2 3]
#  [5 6]]

# 의미
# 모든 행에서
# 1~2열 선택

20
[20 30 40]
[1 2 3]
[2 5]


#### Boolean Indexing & Fancy Indexing

In [ ]:
# -------------------------------------------------
# Boolean Indexing
#
# Boolean Indexing은 조건식을 이용해서
# True에 해당하는 값들만 선택하는 방법이다.
#
# 즉, 배열에서 특정 조건을 만족하는 값들만
# 필터링(filtering)할 때 사용한다.
# -------------------------------------------------

arr = np.array([10, 20, 30, 40, 50])

# 조건 배열 생성
print(arr > 30)

# 결과
# [False False False  True  True]

# 의미
# arr의 각 원소가 조건을 만족하는지 검사한 결과이다.


# -------------------------------------------------
# 조건을 이용한 값 선택

print(arr[arr > 30])

# 결과
# [40 50]

# 의미
# arr > 30 이 True인 위치의 값들만 선택된다.


# -------------------------------------------------
# 다른 조건 예시

print(arr[arr >= 30])   # [30 40 50]
print(arr[arr < 30])    # [10 20]


# -------------------------------------------------
# Boolean Indexing은 데이터 분석에서 매우 중요하다.
#
# 예
# - 특정 조건을 만족하는 데이터 필터링
# - 이상치(outlier) 제거
# - 특정 값 범위 데이터 선택
# -------------------------------------------------


# -------------------------------------------------
# 2차원 배열 Boolean Indexing

arr_2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr_2[arr_2 > 3])

# 결과
# [4 5 6]

# 의미
# 배열 전체에서 조건을 만족하는 값만 선택된다.


# -------------------------------------------------
# Fancy Indexing
#
# Fancy Indexing은 인덱스 배열을 이용해서
# 특정 위치의 값들을 한 번에 선택하는 방법이다.
#
# 일반 인덱싱
# arr[2]
#
# Fancy Indexing
# arr[[1,3,4]]
# -------------------------------------------------

arr = np.array([10, 20, 30, 40, 50])


# -------------------------------------------------
# 여러 인덱스 선택

print(arr[[1, 3, 4]])

# 결과
# [20 40 50]

# 의미
# 인덱스 1, 3, 4에 해당하는 값들을 선택한다.


# -------------------------------------------------
# 인덱스 순서를 바꿀 수도 있다.

print(arr[[4, 2, 0]])

# 결과
# [50 30 10]

# Fancy Indexing은 인덱스 순서대로 값을 가져온다.


# -------------------------------------------------
# 2차원 배열 Fancy Indexing

arr_2 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])


# 특정 행 선택

print(arr_2[[0, 2]])

# 결과
# [[10 20 30]
#  [70 80 90]]

# 의미
# 0번째 행과 2번째 행 선택


# -------------------------------------------------
# 특정 위치 값 선택

print(arr_2[[0,1,2], [2,1,0]])

# 결과
# [30 50 70]

# 의미
# (0,2)
# (1,1)
# (2,0)
# 위치 값 선택

---

## 7. 행렬 연산


In [13]:
# -------------------------------------------------
# NumPy 배열 연산 (Array Operation)
#
# NumPy의 가장 큰 특징은
# "반복문 없이 배열끼리 계산이 가능하다"는 것이다.
#
# 이를 벡터 연산(Vectorized Operation)이라고 한다.
# -------------------------------------------------


# -------------------------------------------------
# 배열 생성

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


# -------------------------------------------------
# Element-wise 연산 (원소별 연산)
#
# NumPy에서는 같은 위치의 원소끼리 연산이 이루어진다.
# 즉, 배열 전체가 아니라 "각 원소별로 계산"된다.
# -------------------------------------------------

print(a + b)  # [5 7 9]

# 계산 과정
# 1 + 4 = 5
# 2 + 5 = 7
# 3 + 6 = 9


print(a - b)  # [-3 -3 -3]

# 계산 과정
# 1 - 4 = -3
# 2 - 5 = -3
# 3 - 6 = -3


print(a * b)  # [ 4 10 18]

# 계산 과정
# 1 * 4 = 4
# 2 * 5 = 10
# 3 * 6 = 18


print(a / b)  # [0.25 0.4 0.5]

# 계산 과정
# 1 / 4
# 2 / 5
# 3 / 6


# -------------------------------------------------
# 스칼라 연산 (Scalar Operation)
#
# 배열과 하나의 숫자를 연산하면
# 모든 원소에 동일한 연산이 적용된다.
# -------------------------------------------------

print(a + 10)   # [11 12 13]

# 계산 과정
# 1 + 10
# 2 + 10
# 3 + 10


print(a * 2)    # [2 4 6]

# 모든 원소에 2를 곱한다.


# -------------------------------------------------
# 배열 연산의 장점
#
# NumPy는 내부적으로 C로 구현되어 있어서
# 반복문보다 훨씬 빠르게 계산된다.
#
# 예 (일반 Python 방식)
#
# for i in range(len(a)):
#     result[i] = a[i] + b[i]
#
# NumPy 방식
#
# a + b
#
# 훨씬 간단하고 빠르다.
# -------------------------------------------------



# =================================================
# 행렬 연산 (Matrix Operation)
# =================================================


# -------------------------------------------------
# 2차원 배열 생성

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])


# -------------------------------------------------
# Element-wise 행렬 연산
#
# 행렬에서도 기본 연산은 원소별로 수행된다.

print(A + B)

# [[ 6  8]
#  [10 12]]


print(A - B)

# [[-4 -4]
#  [-4 -4]]


print(A * B)

# [[ 5 12]
#  [21 32]]

# 의미
# 같은 위치 원소끼리 곱해진다.
#
# (1*5) (2*6)
# (3*7) (4*8)



# -------------------------------------------------
# 행렬 곱 (Matrix Multiplication)
#
# 위의 A * B 는 "행렬곱"이 아니다.
# 그냥 원소별 곱이다.
#
# 진짜 행렬곱은 다음 방식으로 계산한다.
# -------------------------------------------------

print(A @ B)

# 또는

print(np.dot(A, B))


# 결과
# [[19 22]
#  [43 50]]

# 계산 과정
#
# [1 2]   [5 6]
# [3 4] x [7 8]
#
# 첫 번째 행
# 1*5 + 2*7 = 19
# 1*6 + 2*8 = 22
#
# 두 번째 행
# 3*5 + 4*7 = 43
# 3*6 + 4*8 = 50



# -------------------------------------------------
# Element-wise 연산 vs 행렬곱 정리
#
# A * B
# → 원소별 곱
#
# A @ B
# → 행렬곱
#
# np.dot(A, B)
# → 행렬곱
# -------------------------------------------------



# -------------------------------------------------
# 배열 제곱 연산

print(a ** 2)  # [1 4 9]

# 의미
# 각 원소를 제곱한다.


# -------------------------------------------------
# NumPy 수학 함수
#
# NumPy는 다양한 수학 함수를 제공한다.

print(np.sqrt(a))  # 제곱근
print(np.exp(a))   # e^x
print(np.log(a))   # 자연로그


# -------------------------------------------------
# 정리
#
# NumPy 배열 연산 핵심
#
# 1) Element-wise 연산
#    배열의 같은 위치 원소끼리 계산
#
# 2) 스칼라 연산
#    하나의 값이 배열 전체에 적용
#
# 3) 행렬 연산
#    A @ B 또는 np.dot(A,B)
#
# NumPy는 반복문 없이 빠르게 계산할 수 있다.
# -------------------------------------------------

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[11 12 13]


---

## 8. 브로드캐스팅
: 브로드캐스팅은 **크기가 다른 배열을 자동으로 맞춰 연산하는 기능**이다.

In [ ]:
# -------------------------------------------------
# Broadcasting (브로드캐스팅)
#
# 브로드캐스팅은 크기가 다른 배열끼리 연산할 때
# NumPy가 자동으로 배열의 크기를 맞춰주는 기능이다.
#
# 즉, 작은 배열을 큰 배열에 맞게 "확장해서"
# 연산이 가능하도록 만든다.
#
# 덕분에 반복문 없이도 매우 간단하게 계산할 수 있다.
# -------------------------------------------------


# -------------------------------------------------
# 예제 1 : 배열 + 스칼라

arr = np.array([1, 2, 3])

print(arr + 10)  # [11 12 13]

# 계산 과정
# [1, 2, 3]
# +
#   10

# NumPy 내부적으로 이렇게 확장된다.

# [1, 2, 3]
# +
# [10,10,10]

# 결과
# [11,12,13]

# 이것이 브로드캐스팅이다.


# -------------------------------------------------
# 예제 2 : 2차원 배열 + 스칼라

arr_2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr_2 + 10)

# 결과
# [[11 12 13]
#  [14 15 16]]

# 모든 원소에 10이 더해진다.

# 내부적으로는

# [[1,2,3],
#  [4,5,6]]

# +
# [[10,10,10],
#  [10,10,10]]


# -------------------------------------------------
# 예제 3 : 배열 + 배열 (같은 크기)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

# 결과
# [5 7 9]

# 같은 위치의 원소끼리 연산된다.


# -------------------------------------------------
# 예제 4 : 2차원 배열 + 1차원 배열

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([10, 20, 30])

print(A + B)

# 결과
# [[11 22 33]
#  [14 25 36]]

# 계산 과정

# A
# [[1 2 3]
#  [4 5 6]]

# B
# [10 20 30]

# NumPy가 B를 이렇게 확장한다.

# [[10 20 30],
#  [10 20 30]]

# 그리고 연산 수행


# -------------------------------------------------
# Broadcasting 규칙
#
# NumPy는 다음 규칙에 따라 브로드캐스팅을 수행한다.
#
# 1️⃣ 두 배열의 차원을 오른쪽부터 비교한다.
#
# 2️⃣ 두 차원이 같거나
#    한쪽이 1이면 연산 가능하다.
#
# 3️⃣ 그렇지 않으면 오류 발생
# -------------------------------------------------


# -------------------------------------------------
# Broadcasting 가능한 예

A = np.ones((2,3))
B = np.array([10,20,30])

print(A + B)

# shape 비교
#
# A : (2,3)
# B : (3,)
#
# 뒤에서 비교
#
# 3 == 3 → OK
#
# 따라서 브로드캐스팅 가능


# -------------------------------------------------
# Broadcasting 불가능한 예

A = np.ones((2,3))
B = np.array([10,20])

# print(A + B)

# shape 비교
#
# A : (2,3)
# B : (2,)
#
# 뒤에서 비교
#
# 3 != 2
#
# 그리고 둘 중 하나가 1도 아니다.
#
# 따라서 연산 불가능
#
# 오류 발생
# ValueError: operands could not be broadcast together


# -------------------------------------------------
# Broadcasting 실제 활용 예
#
# 데이터 정규화
# 이미지 처리
# 머신러닝 데이터 전처리
# -------------------------------------------------

# 예 : 평균 빼기

data = np.array([
    [170, 65],
    [180, 80],
    [175, 70]
])

mean = np.array([175, 70])

print(data - mean)

# 결과
# [[-5 -5]
#  [ 5 10]
#  [ 0  0]]

# 각 열에 대해 평균을 빼는 작업


# -------------------------------------------------
# 정리
#
# Broadcasting이란
# "크기가 다른 배열끼리 연산할 때
# NumPy가 자동으로 배열 크기를 맞추는 기능"
#
# 핵심 규칙
#
# 1️⃣ 차원을 오른쪽부터 비교
# 2️⃣ 같거나 한쪽이 1이면 가능
#
# NumPy 연산이 강력한 이유는
# 바로 이 브로드캐스팅 때문이다.
# -------------------------------------------------

---

## 9. 배열 형태 변경


In [ ]:
# -------------------------------------------------
# 배열 형태 변경 (Array Shape Manipulation)
#
# NumPy에서는 배열의 "형태(shape)"를 변경할 수 있다.
#
# 예
# (6,)   → 1차원 배열
# (2,3)  → 2행 3열 배열
# (3,2)  → 3행 2열 배열
#
# 단, 배열의 "전체 원소 개수(size)"는 반드시 같아야 한다.
# -------------------------------------------------


# -------------------------------------------------
# reshape()
#
# 배열의 구조(shape)를 변경할 때 사용하는 함수이다.
#
# 조건
# reshape 전후의 size가 동일해야 한다.
# -------------------------------------------------

arr = np.arange(6)

print(arr)
# [0 1 2 3 4 5]

print(arr.shape)
# (6,)


# -------------------------------------------------
# 1차원 → 2차원 변환

arr_2 = arr.reshape(2,3)

print(arr_2)

# [[0 1 2]
#  [3 4 5]]

print(arr_2.shape)
# (2,3)


# -------------------------------------------------
# 다른 형태로 변경

arr_3 = arr.reshape(3,2)

print(arr_3)

# [[0 1]
#  [2 3]
#  [4 5]]


# -------------------------------------------------
# reshape에서 -1 사용
#
# -1을 사용하면 NumPy가 자동으로 크기를 계산한다.

arr_auto = arr.reshape(2,-1)

print(arr_auto)

# [[0 1 2]
#  [3 4 5]]

# 의미
# 행은 2로 고정
# 열은 자동 계산


# -------------------------------------------------
# flatten()
#
# 다차원 배열을 1차원 배열로 변환한다.

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.flatten())

# [1 2 3 4 5 6]


# -------------------------------------------------
# ravel()
#
# flatten과 같은 기능
# 하지만 메모리를 복사하지 않고
# 기존 배열을 참조한다.

print(arr.ravel())

# [1 2 3 4 5 6]


# -------------------------------------------------
# reshape vs flatten
#
# reshape
# → 배열 구조 변경
#
# flatten
# → 항상 1차원 배열 생성
# -------------------------------------------------


# -------------------------------------------------
# transpose (전치 행렬)
#
# 행과 열을 바꾸는 연산이다.

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.T)

# [[1 4]
#  [2 5]
#  [3 6]]

# shape 변화
# (2,3) → (3,2)


# -------------------------------------------------
# reshape 불가능한 경우

arr = np.arange(5)

# print(arr.reshape(2,3))

# 오류 발생
# ValueError

# 이유
# 기존 size = 5
# reshape 후 size = 6
# 원소 개수가 다르기 때문이다.


# -------------------------------------------------
# 정리
#
# reshape()
# → 배열 구조 변경
#
# flatten()
# → 1차원 배열로 변환
#
# ravel()
# → flatten과 유사하지만 메모리 복사 없음
#
# transpose(.T)
# → 행과 열 교환
#
# 핵심 규칙
# reshape 전후 size는 반드시 같아야 한다.
# -------------------------------------------------

---

## 10. axis 개념

In [ ]:
# axis 개념
#
# axis는 "연산이 수행되는 방향"을 의미한다.
#
# 쉽게 말하면
# 어느 방향으로 계산을 할 것인지 지정하는 것이다.
#
# axis = 0 → 행 방향으로 계산
# axis = 1 → 열 방향으로 계산
#
# 처음 보면 헷갈리지만
# "축 방향으로 이동하면서 계산한다"라고 생각하면 이해가 쉽다.
# -------------------------------------------------


# -------------------------------------------------
# 예제 배열 생성

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr)

# 배열 구조
#
# [[1 2 3]
#  [4 5 6]]
#
# shape = (2,3)
# 2행 3열 배열


# -------------------------------------------------
# axis = 0
#
# axis=0은 "행 방향으로 내려가면서" 계산한다.
#
# 즉 같은 열(column)의 값들을 계산한다.

print(np.sum(arr, axis=0))

# 계산 과정
#
# 1 + 4 = 5
# 2 + 5 = 7
# 3 + 6 = 9
#
# 결과
# [5 7 9]


# -------------------------------------------------
# axis = 1
#
# axis=1은 "열 방향으로 이동하면서" 계산한다.
#
# 즉 같은 행(row)의 값들을 계산한다.

print(np.sum(arr, axis=1))

# 계산 과정
#
# 1 + 2 + 3 = 6
# 4 + 5 + 6 = 15
#
# 결과
# [ 6 15 ]


# -------------------------------------------------
# axis 없이 계산

print(np.sum(arr))

# 결과
# 21

# 의미
# 배열 전체 원소를 모두 더한다.


# -------------------------------------------------
# axis는 다양한 함수에서 사용된다.

print(np.mean(arr, axis=0))   # 열 평균
print(np.mean(arr, axis=1))   # 행 평균

print(np.max(arr, axis=0))    # 열 최대값
print(np.max(arr, axis=1))    # 행 최대값

print(np.min(arr, axis=0))    # 열 최소값
print(np.min(arr, axis=1))    # 행 최소값


# -------------------------------------------------
# axis 이해를 돕는 그림
#
# 배열
#
# [[1 2 3]
#  [4 5 6]]
#
# axis = 0
#
# ↓
# ↓
#
# 열 기준 계산
#
# axis = 1
#
# →
# →
#
# 행 기준 계산
# -------------------------------------------------


# -------------------------------------------------
# axis 정리
#
# axis = 0
# → 위에서 아래 방향
# → 열(column) 기준 연산
#
# axis = 1
# → 왼쪽에서 오른쪽 방향
# → 행(row) 기준 연산
#
# NumPy에서
# sum, mean, max, min 등 대부분의 함수는
# axis 옵션을 지원한다.
# -------------------------------------------------

---

## 10. NumPy 수학 함수


In [ ]:
# -------------------------------------------------
# NumPy 통계 함수 (Statistical Functions)
#
# NumPy는 배열 데이터의 통계를 쉽게 계산할 수 있는
# 다양한 함수들을 제공한다.
#
# 대표적인 통계 함수
#
# sum    → 합계
# mean   → 평균
# max    → 최대값
# min    → 최소값
# std    → 표준편차
# var    → 분산
# -------------------------------------------------


arr = np.array([10, 20, 30, 40, 50])


# -------------------------------------------------
# 합계

print(np.sum(arr))   # 150

# 계산
# 10 + 20 + 30 + 40 + 50


# -------------------------------------------------
# 평균

print(np.mean(arr))  # 30

# 계산
# (10 + 20 + 30 + 40 + 50) / 5


# -------------------------------------------------
# 최대값

print(np.max(arr))   # 50


# -------------------------------------------------
# 최소값

print(np.min(arr))   # 10


# -------------------------------------------------
# 표준편차 (Standard Deviation)

print(np.std(arr))

# 데이터가 평균에서 얼마나 퍼져있는지 나타낸다.


# -------------------------------------------------
# 분산 (Variance)

print(np.var(arr))

# 표준편차의 제곱 값


# -------------------------------------------------
# 위치 찾기 함수
#
# argmax → 최대값 위치
# argmin → 최소값 위치

print(np.argmax(arr))  # 4
print(np.argmin(arr))  # 0

# 의미
# arr[4] = 50
# arr[0] = 10


# =================================================
# 2차원 배열 통계
# =================================================


arr_2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


# -------------------------------------------------
# axis 활용

print(np.sum(arr_2, axis=0))

# 결과
# [5 7 9]

# 열 기준 합
#
# 1 + 4
# 2 + 5
# 3 + 6


print(np.sum(arr_2, axis=1))

# 결과
# [ 6 15 ]

# 행 기준 합
#
# 1 + 2 + 3
# 4 + 5 + 6


# -------------------------------------------------
# 평균

print(np.mean(arr_2, axis=0))  # 열 평균
print(np.mean(arr_2, axis=1))  # 행 평균


# =================================================
# NumPy 수학 함수 (Mathematical Functions)
# =================================================
#
# NumPy는 다양한 수학 계산을 지원한다.
#
# sqrt → 제곱근
# exp  → e^x
# log  → 자연로그
# sin  → 사인
# cos  → 코사인
# -------------------------------------------------


arr = np.array([1, 2, 3, 4])


# -------------------------------------------------
# 제곱

print(arr ** 2)

# 결과
# [ 1  4  9 16]


# -------------------------------------------------
# 제곱근

print(np.sqrt(arr))

# 결과
# [1.         1.41421356 1.73205081 2.        ]


# -------------------------------------------------
# 지수 함수

print(np.exp(arr))

# e^1, e^2, e^3 ...


# -------------------------------------------------
# 로그 함수

print(np.log(arr))

# 자연로그


# -------------------------------------------------
# 삼각 함수

print(np.sin(arr))
print(np.cos(arr))


# -------------------------------------------------
# 절대값

arr = np.array([-1, -2, 3, -4])

print(np.abs(arr))

# 결과
# [1 2 3 4]


# -------------------------------------------------
# 정리
#
# 통계 함수
#
# sum
# mean
# max
# min
# std
# var
# argmax
# argmin
#
#
# 수학 함수
#
# sqrt
# exp
# log
# sin
# cos
# abs
#
# NumPy는 이러한 함수들을 배열 전체에
# 벡터 연산 방식으로 적용한다.
# -------------------------------------------------